<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="F515R72" ignored="0" name="Test" tests="6" failures="1" timestamp="29 Sep 2021 08:27:07 GMT" time="3.795" errors="0">
  <testcase name="Fails" time="0.02" classname="POM.DataProviderDemoTest">
    <skipped/>
  </testcase> <!-- Fails -->
  <testcase name="Fails" time="0.001" classname="POM.DataProviderDemoTest">
    <skipped/>
  </testcase> <!-- Fails -->
  <testcase name="Fails" time="0.003" classname="POM.DataProviderDemoTest">
    <skipped/>
  </testcase> <!-- Fails -->
  <testcase name="Fails" time="0.002" classname="POM.DataProviderDemoTest">
    <skipped/>
  </testcase> <!-- Fails -->
  <testcase name="Fails" time="0.004" classname="POM.DataProviderDemoTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at POM.DataProviderDemoTest.Fails(DataProviderDemoTest.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Fails -->
  <testcase name="Name" time="3.323" classname="POM.DataProviderDemoTest"/>
</testsuite> <!-- Test -->
